# ----------------------------------------------------
# This config holds the IP address of the Raspberry Pi
# running udpServerLED where the status information is
# sent to.
# Edit to set new IP address
# ----------------------------------------------------
LEDIPAddress:
  IPAddress: '127.0.0.1'
