name: udpClientLED
main: udpClientLED.Main
version: 0.0.2
author: EmbeddedPi
description: In conjunction udpServerLED, this plugin uses a traffic light LED system to indicate server status on and external RaspberryPi.
commands:
   setLEDIPAddress:
      description: This sets the IP address to send LED status updates to.
      usage: /setLEDIPAddress [ipAddress]
      permission: op
      permission-message: No you don't, your level of omnipotency is sadly lacking!
   listLEDIPAddress:
      description: This list the current IP address to send LED status updates to.
      usage: /listLEDIPAddress 
      permission: op
      permission-message: No you don't, you just aren't worthy!
   updateLEDIPAddress:
      description: This will updatet the IP address if the config.yml has been manually edited.
      usage: /updateLEDIPAddress 
      permission: op
      permission-message: Oh no you don't! 
