name: udpClientLED
main: udpClientLED.Main
version: 0.0.2
commands:
   setLEDIPAddress:
      description: This sets the IP address to send LED status updates to.
      usage: /setLEDIPAddress [ipAddress]
      permission: op
      permission-message: No you don't, your level of omnipotency is sadly lacking!
   listLEDIPAddress:
      description: This list the current IP address to send LED status updates to.
      usage: /listLEDIPAddress 
      permission: op
      permission-message: No you don't, you just aren't worthy!