name: udpClientLED
main: udpClientLED.Main
version: 0.414
author: EmbeddedPi
description: In conjunction udpServerLED, this plugin uses a traffic light LED system to indicate server status on and external RaspberryPi.
commands:
   setUDPIPAddress:
      description: This sets the IP address to send LED status updates to.
      usage: /setUDPIPAddress [ipAddress]
      permission: op
      permission-message: No you don't, your level of omnipotency is sadly lacking!
   listUDPConfig:
      description: This list the current IP address to send LED status updates to.
      usage: /listUDPConfig 
      permission: op
      permission-message: No you don't, you just aren't worthy!
   updateUDPConfig:
      description: This will update the IP address or timeout settings if the config.yml has been manually edited.
      usage: /updateUDPConfig 
      permission: op
      permission-message: Oh no you don't! 
   setUDPTimeout:
      description: This will alter the initial timeout settings when first trying a new IP address.
      usage: /setUDPTimeout [timeout in milliseconds] default 5000
      permission: op
      permission-message: No chance! 
   setUDPShortTimeout:
      description: This will alter the timeout settings for a previously confirmed IP address.
      usage: /setUDPShortTimeout [timeout in milliseconds] default 500
      permission: op
      permission-message: As if! 
